 GET https://kebele-id-renewal-and-issuing-backend.onrender.com/api/v1/kebele/
###
 GET https://kebele-id-renewal-and-issuing-backend.onrender.com/api/v1/id/

 ###

  POST https://kebele-id-renewal-and-issuing-backend.onrender.com/api/v1/admin/login
  Content-Type: application/json

  {
  "phoneNumber":"1234567890",
  "password":"dsdsdfdf"
 }